/*
 * This source file was generated by the Gradle 'init' task
 */
package lab7;

public class JTree {
    Entry root;

    class Entry {
        public Character value;
        public int frequency;
        public Entry leftChild;
        public Entry rightChild;

        Entry(Character v, int f) {
            value = v;
            frequency = f;
        }

        Entry(Character v, int f, Entry left, Entry right) {
            value = v;
            frequency = f;
            leftChild = left;
            rightChild = right;
        }

        public String toString() {
            return (value.toString() + " " + frequency);
        }
    }

    public JTree(Character v, int f) {
        Entry j = new Entry(v, f);
        root = j;
    }

    public JTree(Entry left, Entry right) {
        int combinedFreq = left.frequency + right.frequency;
        Entry j = new Entry(null, combinedFreq, left, right);
        root = j;
    }

    public int getTreeFreq() {
        return root.frequency;
    }
}
