/*
 * Author: Fabien Gardes-Picado & Tyler Eads
 * Date: 2025-06-03
 * Purpose: Lab 7
 * Generated by gradle init function
 */

package lab7;

// JTree is used to construct our code tree, with entries and other JTrees linked together 
public class JTree {
    Entry root;

    class Entry {
        public Character value;
        public int frequency;
        public Entry leftChild;
        public Entry rightChild;
        public Entry parent;

        Entry(Character v, int f) {
            value = v;
            frequency = f;
        }

        Entry(Character v, int f, Entry left, Entry right) {
            value = v;
            frequency = f;
            leftChild = left;
            rightChild = right;
        }

        public String toString() {
            return (value.toString() + " " + frequency);
        }
    }

    public JTree(Character v, int f) {
        Entry j = new Entry(v, f);
        root = j;
    }

    public JTree(Entry left, Entry right) {
        int combinedFreq = left.frequency + right.frequency;
        Entry j = new Entry(null, combinedFreq, left, right);
        root = j;
    }

    public int getTreeFreq() {
        return root.frequency;
    }
}
